'use client';
import {useState} from 'react';

const colleges={
'College of Humanity and Management Sciences':['B.A. English','B.A. Fine and Applied Arts','B.A. Music','B.A. Religious Studies','B.Sc. Accounting','B.Sc. Business Administration','B.Sc. Economics','B.Sc. Finance','B.Sc. Industrial Relations & Personal Management','B.Sc. Mass Communication','B.Sc. Public Administration','B.Sc. Securities and Investment'],
'College of Basic and Applied Sciences':['B.Sc. Applied Geophysics','B.Sc. Biochemistry','B.Sc. Biology','B.Sc. Biotechnology','B.Sc. Chemistry','B.Sc. Computer Science','B.Sc. Software Engineering','B.Sc. Cyber Security','B.Sc. Mathematics','B.Sc. Microbiology','B.Sc. Physics','B.Sc. Physics with Electronics','B.Sc. Geology','B.Sc. Industrial Chemistry','B.Sc. Food Science and Technology'],
'College of Applied Health Sciences':['B.Sc. Nursing Science','B.Sc. Medical Laboratory Science','B.Sc. Public Health','B.Sc. Community Health','B.Sc. Biomedical Laboratory Science','B.Sc. Nutrition and Dietetics']};
const points={A1:10,B2:9,B3:8,C4:7,C5:6,C6:5};
const initialCollege=Object.keys(colleges)[0];
export default function Home(){
 const [college,setCollege]=useState(initialCollege); const [form,setForm]=useState({surname:'',firstName:'',otherName:'',gender:'',dob:'',jamb:'',course:colleges[initialCollege][0],waec:['','','','','']}); const [result,setResult]=useState(null);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const grade=(i,v)=>setForm(x=>({...x,waec:x.waec.map((g,j)=>j===i?v:g)}));
 function calculate(e){e.preventDefault();const j=Number(form.jamb), p=form.waec.map(g=>points[g]); if(!form.surname||!form.firstName||!form.gender||!Number.isFinite(j)||j<0||j>400||p.some(x=>!x)){alert('Complete applicant details, JAMB (0–400), and all five WAEC grades.');return;} const sum=p.reduce((a,b)=>a+b,0), waec=(sum/50)*40, jamb=(j/400)*60,total=waec+jamb; const decision=total>=70?['Admission Recommended','admit']:total>=50?['Further Review','review']:['Not Admitted','reject'];setResult({sum,waec,jamb,total,decision});}
 function reset(){setForm({surname:'',firstName:'',otherName:'',gender:'',dob:'',jamb:'',course:colleges[college][0],waec:['','','','','']});setResult(null)}
 return <main className="container"><header className="hero"><h1>AI-Powered University Admissions System</h1><p>JAMB + five WAEC subjects • automated score calculation and admission assessment</p></header>
 <form className="grid" onSubmit={calculate}>
 <section className="card"><h2>Applicant Details</h2>{[['surname','Surname'],['firstName','First Name'],['otherName','Other Name']].map(([k,l])=><div className="field" key={k}><label>{l}</label><input value={form[k]} onChange={e=>set(k,e.target.value)}/></div>)}<div className="field"><label>Gender</label><select value={form.gender} onChange={e=>set('gender',e.target.value)}><option value="">Select gender</option><option>Male</option><option>Female</option><option>Other</option></select></div><div className="field"><label>Date of Birth</label><input type="date" value={form.dob} onChange={e=>set('dob',e.target.value)}/></div></section>
 <section className="card"><h2>College & Course</h2><div className="field"><label>College</label><select value={college} onChange={e=>{const c=e.target.value;setCollege(c);setForm(x=>({...x,course:colleges[c][0]}));setResult(null)}}>{Object.keys(colleges).map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>Course</label><select value={form.course} onChange={e=>set('course',e.target.value)}>{colleges[college].map(c=><option key={c}>{c}</option>)}</select></div><div className="field"><label>JAMB Score (0–400)</label><input type="number" min="0" max="400" value={form.jamb} onChange={e=>set('jamb',e.target.value)}/></div><p className="note">JAMB Aggregate = (JAMB Score ÷ 400) × 60</p></section>
 <section className="card full"><h2>WAEC Results — Five Subjects</h2><div className="subjects">{form.waec.map((g,i)=><div className="subject" key={i}><label>Subject {i+1}</label><select value={g} onChange={e=>grade(i,e.target.value)}><option value="">Select grade</option>{Object.entries(points).map(([x,p])=><option key={x} value={x}>{x} — {p} points</option>)}</select></div>)}</div><p className="note">WAEC Aggregate = (Sum of five WAEC points ÷ 50) × 40</p></section>
 <section className="card full"><div className="actions"><button>Calculate Admission Decision</button><button type="button" className="alt" onClick={reset}>Reset</button></div></section></form>
 {result&&<section className="card result" style={{marginTop:18}}><h2>Admission Assessment</h2><p><b>Applicant:</b> {form.surname} {form.firstName} {form.otherName}</p><p><b>Gender:</b> {form.gender} &nbsp; <b>College:</b> {college} &nbsp; <b>Course:</b> {form.course}</p><div className="metrics"><div className="metric">WAEC Points Sum<b>{result.sum}/50</b></div><div className="metric">WAEC Aggregate<b>{result.waec.toFixed(2)}/40</b></div><div className="metric">JAMB Aggregate<b>{result.jamb.toFixed(2)}/60</b></div></div><p>Total Score</p><div className="total">{result.total.toFixed(2)} / 100</div><p><span className={'badge '+result.decision[1]}>{result.decision[0]}</span></p><p className="note">Prototype decision thresholds: 70+ Admission Recommended; 50–69.99 Further Review; below 50 Not Admitted. Replace these thresholds with the university’s officially approved policy before production deployment.</p></section>}
 <div className="footer">Next.js • Responsive CSS • Vercel-ready</div></main>}
